[package]
name = "snm"
version = "0.1.0"
authors = ["numtostr <vikasraj1911@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.0.0-beta.2"
dirs-next = "2.0.0"
serde = { version = "1.0.118", features = ["derive"] }
tar = "0.4.30"
tempfile = "3.1.0"
ureq = { version = "1.5.4", features = ["json", "charset"] }
xz2 = "0.1.6"
zip = "0.5.9"
