[package]
name = "snm"
version = "0.1.0"
description = "Smol and Stupid Node Manager"
authors = ["Vikas Raj <sudo@vikasraj.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.36"
clap = "3.0.0-beta.2"
clap_generate = "3.0.0-beta.2"
dirs-next = "2.0.0"
semver = "0.11.0"
serde = { version = "1.0.118", features = ["derive"] }
tar = "0.4.30"
tempfile = "3.1.0"
ureq = { version = "2.0.0-rc4", features = ["json"] }
xz2 = "0.1.6"
zip = "0.5.9"

[profile.release]
lto = true
codegen-units = 1
opt-level = 'z'
